chore: update readme
MESH-Research/Pilcrow pull request #1988
Opened 2023-10-09 20:00 UTC by wreality

2023-10-20 17:57 UTC, wreality commented
@all-contributors please add @wreality for code, mentoring, infrastructure and review

2023-11-01 19:43 UTC, wreality commented
Ready for review!  For rendered previews see the netlify deploy linked above.

2023-11-02 16:44 UTC, gmeben requested changes
This is a very beautiful-looking update to the documentation. I have some suggestions. 

I was not able to get the `docs` site working locally following the existing instructions: https://deploy-preview-1988--eloquent-galileo-3be94a.netlify.app/developers/documentation.html#serving-test-docs-using-lando

2023-11-03 17:48 UTC, wreality commented on docs/install/index.md
> +MAIL_FROM_NAME="Pilcrow Mailer"   # <-- Supply a name to be used as the sender for mail
Resolved in commit

2023-11-03 17:50 UTC, wreality commented
> I was not able to get the `docs` site working locally following the existing instructions: https://deploy-preview-1988--eloquent-galileo-3be94a.netlify.app/developers/documentation.html#serving-test-docs-using-lando

This is fixed now.  I neglected to move the lando config over from the old docs directory.  Everything should be address now.

2023-11-03 23:07 UTC, gmeben approved these changes
I encounter a 404 when I attempt to visit the Team page, but all the other pages load and look fine. I'll attribute that to something missing locally because it loads in the deployment preview. That can be troubleshooted later. 

<img width="874" alt="Screenshot of the Team page with Chrome's developer tools open. An error message for contributors.data.ts reads, 'The 'path' argument must be of type string or an instance of Buffer or URL. Received undefined'" src="https://github.com/MESH-Research/Pilcrow/assets/2668987/1a3ace88-9ab8-4dff-b0af-e6e97074d9aa">

2023-11-04 00:49 UTC, merged